import { vi } from 'vitest';

export function createAppServicesMock() {
  return {
    AUTH_EXPIRED_EVENT: 'hemodinks:auth-expired',
    DEFAULT_SYSTEM_SETTINGS: {
      id: 1,
      nomeEmpresa: 'Hemodinks',
      fotoEmpresa: null,
      dataCadastro: '',
      dataAtualizacao: null,
    },
    authenticate: vi.fn(),
    refreshSession: vi.fn(),
    listPublicClinics: vi.fn(),
    listPlatformClinics: vi.fn(),
    createPlatformClinic: vi.fn(),
    updatePlatformClinic: vi.fn(),
    deactivatePlatformClinic: vi.fn(),
    listSessionClinics: vi.fn(),
    selectSessionClinic: vi.fn(),
    completeAgendaEvent: vi.fn(),
    createAgendaEvent: vi.fn(),
    deleteAgendaEvent: vi.fn(),
    getAgendaEvents: vi.fn(),
    getAgendaMedicalUsers: vi.fn(),
    getAgendaNotificationRecipientOptions: vi.fn(),
    getBrazilPublicHolidays: vi.fn(),
    markAgendaNotificationsAsRead: vi.fn(),
    updateAgendaEvent: vi.fn(),
    getDashboardNotifications: vi.fn(),
    getDashboardSummary: vi.fn(),
    getCurrentLicenca: vi.fn(),
    getSystemSettings: vi.fn(),
    getSystemSettingsCompanyPhoto: vi.fn(),
    getAllCbhpmGeral: vi.fn(),
    getCbhpmGeral: vi.fn(),
    getConvenios: vi.fn(),
    getHospitais: vi.fn(),
    getMedicalGroup: vi.fn(),
    getMedicalGroups: vi.fn(),
    getScopedMedicalUsers: vi.fn(),
    getOpmeFornecedores: vi.fn(),
    getUsers: vi.fn(),
    getUser: vi.fn(),
    getUserProfilePhoto: vi.fn(),
    getPaciente: vi.fn(),
    getPacienteFinanceiroResumo: vi.fn(),
    getPacienteObservacoes: vi.fn(),
    getPacientes: vi.fn(),
    createPacienteObservacao: vi.fn(),
    markPacienteObservacoesAsRead: vi.fn(),
    createUser: vi.fn(),
    createPaciente: vi.fn(),
    updatePaciente: vi.fn(),
    deletePaciente: vi.fn(),
    uploadPacienteArquivo: vi.fn(),
    deletePacienteArquivo: vi.fn(),
    downloadPacienteArquivo: vi.fn(),
    updateUser: vi.fn(),
    deleteUser: vi.fn(),
    downloadUserArquivo: vi.fn(),
    changePassword: vi.fn(),
    confirmPasswordReset: vi.fn(),
    resetPassword: vi.fn(),
    updateSystemSettings: vi.fn(),
  };
}
