import { vi } from "vitest";

export function createBillingServicesMock() {
  return {
    getAtendimentos: vi.fn(),
    getFaturamentos: vi.fn(),
    getContasReceber: vi.fn(),
    getConvenioProcedimentoPrecos: vi.fn(),
    getPacientes: vi.fn(),
    getHospitais: vi.fn(),
    getFinanceiroResumo: vi.fn(),
    createAtendimento: vi.fn(),
    updateAtendimento: vi.fn(),
    deleteAtendimento: vi.fn(),
    createFaturamento: vi.fn(),
    updateFaturamento: vi.fn(),
    deleteFaturamento: vi.fn(),
    updateFaturamentoStatus: vi.fn(),
    registrarRetornoFaturamento: vi.fn(),
    registrarRecursoGlosa: vi.fn(),
    gerarContaReceber: vi.fn(),
    registrarRecebimento: vi.fn(),
    estornarRecebimento: vi.fn(),
    saveConvenioProcedimentoPreco: vi.fn(),
    uploadComprovanteRecebimento: vi.fn(),
    downloadComprovanteRecebimento: vi.fn(),
    searchContasReceber: vi.fn(),
    updateFaturamentoItem: vi.fn(),
    getCbhpmGeral: vi.fn(),
    updateGlosa: vi.fn(),
    deleteGlosa: vi.fn(),
    updateRecursoGlosa: vi.fn(),
    deleteRecursoGlosa: vi.fn(),
    updateContaReceber: vi.fn(),
    cancelContaReceber: vi.fn(),
    updateConvenioProcedimentoPreco: vi.fn(),
    deactivateConvenioProcedimentoPreco: vi.fn(),
  };
}
