import type { PacienteExportFormat, PacienteExportScope, PacienteFilters } from '../../appTypes';
import type { Convenio, MedicalUserOption, Paciente } from '../../types';

export type PatientListProps = {
  pacientes: Paciente[];
  pacientesLoading: boolean;
  pacientesError: string;
  pacienteSuccessMessage: string;
  pacientesTotalItems: number;
  pacienteVisibleStart: number;
  pacienteVisibleEnd: number;
  pacienteCurrentPage: number;
  pacienteTotalPages: number;
  pacienteSearchTerm: string;
  sortBy: string;
  sortDirection: 'asc' | 'desc';
  pacienteFilters: PacienteFilters;
  pacienteExportLoading: PacienteExportFormat | null;
  pacienteExportScope: PacienteExportScope;
  sessionToken: string;
  canCreatePatients: boolean;
  canEditPatients: boolean;
  canDeletePatients: boolean;
  canManageObservacoes: boolean;
  patientReadOnly: boolean;
  isAdmin: boolean;
  isTeam: boolean;
  medicalUsers: MedicalUserOption[];
  convenios: Convenio[];
  onSearchChange: (value: string) => void;
  onFiltersChange: (filters: PacienteFilters | ((current: PacienteFilters) => PacienteFilters)) => void;
  onClearFilters: () => void;
  onExportScopeChange: (scope: PacienteExportScope) => void;
  onPageChange: (page: number | ((current: number) => number)) => void;
  onSortChange: (field: string) => void;
  onRefresh: () => void;
  onOpenNewPacienteForm: () => void;
  onExportPacientes: (format: PacienteExportFormat) => void | Promise<void>;
  onEditPaciente: (paciente: Paciente) => void | Promise<void>;
  onDeletePaciente: (paciente: Paciente) => void | Promise<void>;
  onOpenPacienteFiles: (paciente: Paciente) => void | Promise<void>;
  onOpenPacienteObservacoes: (paciente: Paciente) => void | Promise<void>;
  onSelectPatientInfo: (paciente: Paciente) => void;
};
