import type { TutorialConfig } from '../tutorialTypes';

export const reportsTutorial = {
  id: 'reports-analytics',
  view: 'reports',
  title: 'Missão: dominar os relatórios',
  description: 'Aprenda a combinar filtros e interpretar os indicadores encontrados.',
  version: 2,
  preflightAllTargets: true,
  steps: [
    {
      id: 'overview',
      target: '[data-tour="reports-overview"]',
      title: 'Central de análise',
      objective: 'Reconheça a área de relatórios antes de começar a consulta.',
      narration: {
        text: 'Esta é a central de relatórios. Aqui, você pode consultar atendimentos e informações de faturamento. Todos os resultados respeitam as permissões do seu perfil.',
        audio: '/tutorials/audio/reports/overview.mp3',
      },
      action: 'continue',
      side: 'bottom',
      align: 'center',
    },
    {
      id: 'filters',
      target: '[data-tour="reports-filters"]',
      title: 'Prepare a consulta',
      objective: 'Conheça o painel que reúne todos os critérios disponíveis.',
      narration: {
        text: 'Este painel reúne os critérios da consulta. Você pode combinar período, médicos, equipes, hospitais, convênios, procedimentos, fornecedores, situação e regime. Quanto mais específicos forem os filtros, mais preciso será o resultado.',
        audio: '/tutorials/audio/reports/filters.mp3',
      },
      action: 'continue',
      side: 'bottom',
      align: 'start',
    },
    {
      id: 'period',
      target: '[data-tour="reports-period"]',
      title: 'Defina o período',
      objective: 'Clique em um dos campos de Cirurgias Consolidadas para avançar.',
      narration: {
        text: 'Comece definindo o período de Cirurgias Consolidadas. Clique em um dos campos de data destacados. O tutorial avançará somente depois dessa ação.',
        audio: '/tutorials/audio/reports/period.mp3',
      },
      action: 'click',
      interaction: { type: 'click', target: '[data-tour="reports-period"]' },
      side: 'bottom',
      align: 'start',
    },
    {
      id: 'combined-filters',
      target: '[data-tour="reports-combined-filters"]',
      title: 'Refine sem expor dados',
      objective: 'Entenda como usar os filtros combináveis da consulta.',
      narration: {
        text: 'Agora, combine os demais filtros para refinar a análise. Durante este treinamento, selecione somente opções fictícias e preparadas para demonstração. Nenhum dado real deve ser utilizado.',
        audio: '/tutorials/audio/reports/combined-filters.mp3',
      },
      action: 'continue',
      side: 'top',
      align: 'start',
    },
    {
      id: 'apply',
      target: '[data-tour="reports-apply"]',
      title: 'Execute a consulta',
      objective: 'Clique em Consultar para aplicar os critérios selecionados.',
      narration: {
        text: 'Quando terminar de escolher os critérios, clique em Consultar. O sistema atualizará os indicadores e a lista de resultados. O tutorial não executará essa ação por você.',
        audio: '/tutorials/audio/reports/apply.mp3',
      },
      action: 'click',
      interaction: { type: 'click', target: '[data-tour="reports-apply"]' },
      side: 'top',
      align: 'center',
    },
    {
      id: 'summary',
      target: '[data-tour="reports-summary"]',
      title: 'Leia os indicadores',
      objective: 'Confira a visão consolidada do resultado.',
      narration: {
        text: 'Estes cartões resumem a consulta atual. Eles apresentam valores faturados e líquidos, glosas, pagamentos, quantidade de atendimentos e materiais especiais, conhecidos como OPME.',
        audio: '/tutorials/audio/reports/summary.mp3',
        pronunciationKeys: ['OPME'],
      },
      action: 'continue',
      side: 'top',
      align: 'center',
    },
    {
      id: 'results',
      target: '[data-tour="reports-results"]',
      title: 'Missão concluída',
      objective: 'Use a lista detalhada para conferir o resultado da análise.',
      narration: {
        text: 'A lista detalhada apresenta os atendimentos encontrados. A partir dela, você pode consultar procedimentos e a lista de verificação de cada registro, conforme a sua permissão. Missão concluída. Agora você já sabe preparar e interpretar uma consulta de relatórios.',
        audio: '/tutorials/audio/reports/results.mp3',
      },
      action: 'continue',
      side: 'top',
      align: 'center',
    },
  ],
} satisfies TutorialConfig;
