import type { TutorialConfig } from '../tutorialTypes';

export const reportsTutorial = {
  id: 'reports-analytics',
  view: 'reports',
  title: 'Missão: dominar os relatórios',
  description: 'Aprenda a combinar filtros e interpretar os indicadores encontrados.',
  preflightAllTargets: true,
  steps: [
    {
      id: 'overview',
      target: '[data-tour="reports-overview"]',
      title: 'Central de análise',
      objective: 'Reconheça a área de relatórios antes de começar a consulta.',
      narration: 'Esta é a central de relatórios. Aqui você combina critérios para analisar atendimentos e faturamento usando somente dados autorizados para o seu perfil.',
      action: 'continue',
      side: 'bottom',
      align: 'center',
    },
    {
      id: 'filters',
      target: '[data-tour="reports-filters"]',
      title: 'Prepare a consulta',
      objective: 'Conheça o painel que reúne todos os critérios disponíveis.',
      narration: 'O painel de consulta reúne datas, médicos, equipes, hospitais, convênios, procedimentos, fornecedores, status e regime. Você pode combinar vários critérios.',
      action: 'continue',
      side: 'bottom',
      align: 'start',
    },
    {
      id: 'period',
      target: '[data-tour="reports-period"]',
      title: 'Defina o período',
      objective: 'Clique em um dos campos de data do atendimento para avançar.',
      narration: 'Comece pelo período do atendimento. Clique em um dos dois campos destacados. A missão só avançará depois da sua ação.',
      action: 'click',
      side: 'bottom',
      align: 'start',
    },
    {
      id: 'combined-filters',
      target: '[data-tour="reports-combined-filters"]',
      title: 'Refine sem expor dados',
      objective: 'Entenda como usar os filtros combináveis da consulta.',
      narration: 'Use estes filtros para refinar a análise. Em homologação, escolha somente opções fictícias e sanitizadas. Nenhum dado real faz parte desta missão.',
      action: 'continue',
      side: 'top',
      align: 'start',
    },
    {
      id: 'apply',
      target: '[data-tour="reports-apply"]',
      title: 'Execute a consulta',
      objective: 'Clique em Consultar para aplicar os critérios selecionados.',
      narration: 'Quando os critérios estiverem prontos, clique em Consultar. O botão permanece totalmente funcional e a missão não executará a ação por você.',
      action: 'click',
      side: 'top',
      align: 'center',
    },
    {
      id: 'summary',
      target: '[data-tour="reports-summary"]',
      title: 'Leia os indicadores',
      objective: 'Confira a visão consolidada do resultado.',
      narration: 'Os cartões resumem valores faturados, líquidos, glosas, pagamentos, atendimentos e O P M E. Eles refletem apenas o resultado da consulta atual.',
      action: 'continue',
      side: 'top',
      align: 'center',
    },
    {
      id: 'results',
      target: '[data-tour="reports-results"]',
      title: 'Missão concluída',
      objective: 'Use a lista detalhada para conferir o resultado da análise.',
      narration: 'A lista detalhada apresenta os atendimentos encontrados e permite abrir procedimentos e checklist. Missão concluída. Você já sabe criar uma consulta analítica.',
      action: 'continue',
      side: 'top',
      align: 'center',
    },
  ],
} satisfies TutorialConfig;
